global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'myapp-node'
    static_configs:
      - targets: ['patient-survey-app-cg.uksouth.azurecontainer.io:9100']

  - job_name: 'patient-survey-app'
    static_configs:
      - targets: ['patient-survey-app-cg.uksouth.azurecontainer.io:8001']
