global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'patient_survey_app'
    static_configs:
      - targets: ['10.0.0.4:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.0.4:9100']
