global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'myapp-node'
    static_configs:
      - targets: ['patient-survey-app-cg.uksouth.azurecontainer.io:9100']

  - job_name: 'patient-survey-app'
    static_configs:
      - targets: ['patient-survey-app-cg.uksouth.azurecontainer.io:8001']

  # Optional: scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-survey.uksouth.azurecontainer.io:9090']
