global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Node exporter / container stats for the app
  - job_name: 'myapp-node'
    static_configs:
      - targets: ['patient-survey-app-cg.uksouth.azurecontainer.io:9100']

  # Python app metrics
  - job_name: 'patient-survey-app'
    static_configs:
      - targets: ['patient-survey-app-cg.uksouth.azurecontainer.io:8001']
