global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Patient Survey App (CLI app metrics on 8001)
  - job_name: 'patient-survey-app'
    static_configs:
      - targets: ['${APP_IP}:8001']

  # Node Exporter (inside your app container)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['${APP_IP}:9100']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(node_cpu.*|node_memory.*|node_filesystem.*)'
        action: keep
