global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'patient-survey-app'
    static_configs:
      - targets: ['survey-app.uksouth.azurecontainer.io:8001']

  - job_name: 'myapp-node'
    static_configs:
      - targets: ['survey-app.uksouth.azurecontainer.io:9100']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(node_cpu.*|node_memory.*|node_filesystem.*)'
        action: keep
