global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  # Example: if app exposes metrics on port 8000
  - job_name: 'feedback-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
