global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'patient_survey_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['DYNAMIC_APP_IP:8000']  # Changed placeholder
    scrape_interval: 10s
    scrape_timeout: 8s

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['DYNAMIC_APP_IP:9100']  # Same placeholder
