global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # external Azure targets
  - job_name: 'myapp-node'
    static_configs:
      - targets: ['survey-app.uksouth.azurecontainer.io:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'patient-survey-app'
    static_configs:
      - targets: ['survey-app.uksouth.azurecontainer.io:8001']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # local node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
