version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "9100:9100"  
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    restart: always
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      # SMTP Configuration for Alerts
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GRAFANA_EMAIL}
      - GF_SMTP_PASSWORD=${GRAFANA_EMAIL_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GRAFANA_EMAIL}
      - GF_SMTP_FROM_NAME=Grafana-Alerts
      - GF_SMTP_SKIP_VERIFY=true  # Useful for development
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - monitoring-net
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9101:9100"
    networks:
      - monitoring-net
    restart: always

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring-net:
    driver: bridge
