pipeline {
  agent {
    docker {
      image 'python:3.10-slim'
      args '-u root'
    }
  }

  environment {
    VENV_DIR = 'venv'
  }

  options {
    timeout(time: 30, unit: 'MINUTES')
  }

  stages {
    stage('Install Dependencies') {
      steps {
        sh '''
          apt-get update && apt-get install -y default-libmysqlclient-dev gcc
          python -m venv ${VENV_DIR}
          . ${VENV_DIR}/bin/activate && pip install --upgrade pip
          . ${VENV_DIR}/bin/activate && pip install -r requirements.txt
        '''
      }
    }

    stage('Run Tests') {
      steps {
        sh '''
          . ${VENV_DIR}/bin/activate
          pytest tests --junitxml=test-results/results.xml
        '''
      }
    }
  }

  post {
    always {
      junit 'test-results/results.xml'
      cleanWs()
    }
  }
}
